
name: Create R package release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  make_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container:
      image: openapx/rbin:latest-ubuntu
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      env:
        ACTION_TOKEN: ${{ github.token }}

    steps:

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          path: src

      - name: Set up environment
        run: |
          apt-get reinstall ca-certificates -y
          update-ca-certificates
          mv src /src
          chmod u+rx-w /src/.scripts/*.sh
          mkdir /assets

      - name: Build R package
        run: /src/.scripts/build-r-package.sh

      - name: Create release 
        run: /src/.scripts/create-release.sh txflow.service
          